name: snaplock_backend
description: "Backend REST em Dart para o projeto SnapLock (Web e Mobile)"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  sqlite3: ^2.4.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.0
  uuid: ^4.3.3
  http_parser: ^4.0.0
  cron: ^0.6.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0
