name: snaplock_backend
description: API Dart do SnapLock
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  mailer: ^6.1.0
  mysql_client: ^0.0.27
  shelf: ^1.4.1
  shelf_router: ^1.1.4